all:
  project_name: 'Sagori_8'
  root: '/scr1/users/leej39/Sagori_123/anvio_meta_8'
  coassembly_yaml: '/scr1/users/leej39/Sagori_123/mapping.yml'
  contig: '/scr1/users/leej39/Sagori_123/sunbeam_output/assembly/coassembly/early8_final_contigs.fa'
  fastq_dir: '/scr1/users/leej39/Sagori_123/sunbeam_output/qc/decontam'
  admin_email: 'junglee0713@gmail.com' 

reformat:
  min_contig_length: 1000

mapping:
  threads: 4

hmm:
  threads: 4

ncbi_cog:
  threads: 8

scg_taxonomy:
  threads: 4

centrifuge:
  threads: 4
  centrifuge_db: '/mnt/isilon/microbiome/analysis/biodata/centrifuge/p+h+v/p+h+v'

profile:
  threads: 4
